### PR TITLE
adding csv loading functionality for windows

### PR DESCRIPTION
**Pull request by gtm1235**
Added functionality to test for system os to allow csv loading on windows, linux, mac.  When loading under windows there was an error due to incorrect splitting of the file path and naming entity set.  Error stating FHIR standards are not followed.

### CODE REVIEW

**Review by gtm1235 — COMMENTED** [review]
Removed specificity in platforms to accommodate older versions of python and all platforms other than windows per sys documentation

**Review by gtm1235 — COMMENTED** [review]
Added functionality for earlier versions of python and all versions other than windows per sys.platform documentation

**Comment by dyuliu** [comment]
Thank you @gtm1235 for your contribution.

Looks that there is a minor style error (check the Github Action checking results). Can you fix it in this PR?

image

**Comment by gtm1235** [comment]
I will and thank you for your patience.. Trying to fit this in during work
hours and should have focused! I'll check the reformat. Have a good day.

Regards,
Gennaro

**Review by gtm1235 — COMMENTED** [review]
Added two spaces in between classes and library according to PEP8 standards

**Comment by gtm1235** [comment]
Is there anything further I need to do? I see that The last commit passed all checks.  Do I close the pull request or wait for approval?  Please let me know if you need anything more and thanks!
Regards,
Gennaro

**Review by gtm1235 — COMMENTED** [review]
Correctly sorted and grouped imports using isort

**Review by gtm1235 — COMMENTED** [review]
I apologize for the extra work .. isort cleared the imports.  I looked at your cleared code and readded the space isort removed.  Thanks.

**Comment by dyuliu** [comment]
Thank you @gtm1235 , the code looks perfect now.

My question now is what is the **empty** file `cardea/data_loader/backup.gpg ` for?

I think I will remove it before I make a merge.

**Comment by gtm1235** [comment]
That was an inadvertent add-on due to an incorrect parameter during a push
that required an encryption key to be added.  I forgot to delete it.  Thank
you for your patience!  Have a great day and thank you for letting me be a
part of the development!

Kind regards,

Gennaro T. Maida
Chief Medical Technology Officer, BetweenMD
P   (928)-221-1870
E   ***@***.***
W   www.betweenmd.com
<https://www.linkedin.com/in/gennaro-maida-218127a/>

[image: Gallery Image]

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
‌
ᐧ

**Pull request merged**
